name: "Terraform Destroy"

on:
  push:
    branches: destroy

jobs:
  terraform:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Destroy Staging
        run: terraform destroy -var-file=tfvars/stg.tfvars -auto-approve -input=false