name: "Terraform"

on:
  pull_request:
    branches: release/staging

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Apply Staging
        if: github.ref == 'refs/heads/releases/staging' && github.event_name == 'push'
        run: terraform apply -var-file=tfvars/stg.tfvars -auto-approve -input=false
