name: "Terraform Apply to Staging"

on:
  push:
    branches: release/staging

jobs:
  terraform:
    name: "Terraform Apply to Staging"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply Staging
        id: stg-apply
        run: terraform apply -var-file=tfvars/stg.tfvars -auto-approve -input=false

      - uses: actions/github-script@v6
        env:
          STG_APPLY: "terraform\n${{ steps.stg-apply.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `
            <details><summary>Show Staging Apply</summary>

            \`\`\`\n
            ${process.env.STG_APPLY}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
